version: 0.2
phases:
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - SHA1TIMESTAMP="$(date +%s | sha1sum | awk '{print substr($1,1,7)}')"
    - echo $SHA1TIMESTAMP
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build -t consul:latest .
    - docker tag consul:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/consul:$SHA1TIMESTAMP
    - docker tag consul:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/consul:latest
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/consul:$SHA1TIMESTAMP
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/consul:latest
cache:
  paths:
  - /var/lib/docker/image